apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rizurin-app-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.rizurin.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rizurin-app-api
                port:
                  number: 80
