apiVersion: v1
kind: Service
metadata:
  name: rizurin-app-api
  namespace: rizurin
  labels:
    app: rizurin-app-api
spec:
  selector:
    app: rizurin-app-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
